version: "3.8"
services:
    app:
        image: cherrypy_app
        build:
            context: .
            network: host
            dockerfile: Dockerfile.app
        volumes:
            - www:/app/www
        #deploy:
        #    replicas: 5
    nginx:
        image: nginx
        configs:
            - source: nginx_conf
              target: /etc/nginx/nginx.conf       
        ports:
            - 8081:80
volumes:
    www:
configs:
    nginx_conf:
        file: nginx.conf


