# MongoDB data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  namespace: egs-mixit
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

# Opensearch data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: os-data
  namespace: egs-mixit
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Mi

# Graylog data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-data
  namespace: egs-mixit
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Mi

# Graylog journal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-journal
  namespace: egs-mixit
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

# Grafana data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: egs-mixit
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
