#Use the official Python image as the base image.
FROM python:3.9

# Set the working directory.
WORKDIR /app

# Copy the file from your host to your current location.

COPY requirements.txt .

#Install any needed packages specified in requirements.txt

RUN pip install --trusted-host --no-cache-dir -r requirements.txt

#Copy the rest of your app's source code from your host to your image filesystem.

COPY . .

#Expose port 8010

EXPOSE 8010

#Run app.py when the container launches.

CMD ["python", "app.py"]
